import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import Header from '@/shared/components/Header'
import Footer from '@/shared/components/Footer'

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Encoteki',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        {' '}
        <div className="flex min-h-screen flex-col justify-between">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
